version: "v1"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - 80:4000
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - 4000:4173
